- name: 执行基础环境配置
  hosts: all
  become: yes
  roles:
    - base-deploy
  tags:
    - base

- name: 部署 NFS
  hosts: all
  become: yes
  roles:
    - nfs
  tags:
    - nfs

- name: 安装 Docker
  hosts: all
  become: yes
  roles:
    - docker
  tags:
    - docker

- name: 安装 Harbor
  hosts: all
  become: yes
  roles:
  - harbor
  tags:
  - harbor

- name: 部署 Ceph 集群
  hosts: all
  become: yes
  roles:
    - role: cephadm
      when: enable_cephadm | default(false)
  tags:
    - cephadm

- name: 配置containerd
  hosts: all
  become: yes
  roles:
    - containerd
  tags:
    - containerd

- name: 配置k8s
  hosts: all
  become: yes
  roles:
    - k8s-deploy
  tags:
    - k8s

- name: Rook-Ceph 对接 k8s
  hosts: all
  become: yes
  roles:
    - role: rook-ceph
      when: enable_rook_ceph | default(false)
  tags:
    - rook-ceph
